-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 19:26:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hichikala
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hichikala
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hichikala` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_persian_ci ;
USE `hichikala` ;

-- -----------------------------------------------------
-- Table `hichikala`.`managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`managers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `name` VARCHAR(60) NULL,
  `family` VARCHAR(60) NULL,
  `rate` TINYINT(1) NULL,
  `status` TINYINT(1) NULL,
  `avatar` VARCHAR(80) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`customers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `name` VARCHAR(60) NULL,
  `family` VARCHAR(60) NULL,
  `phone` VARCHAR(15) NULL,
  `phone_pass` VARCHAR(30) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 10,
  `address` VARCHAR(250) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`blogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`blogs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `min_content` TEXT NOT NULL,
  `status` TINYINT(1) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`products_attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`products_attributes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hichikala`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`products` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NULL,
  `min_content` TEXT NULL,
  `max_content` TEXT NULL,
  `brand` VARCHAR(60) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `sku` VARCHAR(150) NULL,
  `slug` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `products_attributes_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_products_attributes1_idx` (`products_attributes_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_products_attributes1`
    FOREIGN KEY (`products_attributes_id`)
    REFERENCES `hichikala`.`products_attributes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`generals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`generals` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title_about` VARCHAR(100) NOT NULL,
  `min_content_about` TEXT NULL,
  `max_content_about` TEXT NULL,
  `phone_number_store` VARCHAR(20) NULL,
  `email_store` VARCHAR(60) NULL,
  `address_store` VARCHAR(200) NULL,
  `response_time_store` VARCHAR(100) NULL,
  `link_telegram_store` VARCHAR(60) NULL,
  `link_instagram_store` VARCHAR(60) NULL,
  `title_home` VARCHAR(100) NULL,
  `min_content_home` TEXT NULL,
  `max_content_home` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `comment` TEXT NOT NULL,
  `status` TINYINT(1) NULL,
  `table_name` VARCHAR(100) NOT NULL,
  `tables_id` BIGINT NOT NULL,
  `action` VARCHAR(50) NOT NULL DEFAULT 'insert',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `customers_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_blogs_customers1_idx` (`customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_blogs_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `hichikala`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`home_sliders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`home_sliders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `min_content` TEXT NOT NULL,
  `max_content` TEXT NULL,
  `status` TINYINT(1) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`categories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description_category` VARCHAR(255) NULL,
  `description_page` VARCHAR(255) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `categories_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `hichikala`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`transactions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `count` TINYINT NULL,
  `price` INT NULL,
  `payment` TINYINT NULL,
  `process` TEXT NULL,
  `status` TINYINT(1) NULL,
  `date_send` DATETIME NULL,
  `authority` VARCHAR(60) NULL,
  `refid` INT NULL,
  `amount_mony` INT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `customers_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `customers_id`),
  INDEX `fk_transaction_customers1_idx` (`customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `hichikala`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`patterns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`patterns` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `products_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `products_id`),
  INDEX `fk_patterns_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_patterns_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `hichikala`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`sizes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `products_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `products_id`),
  INDEX `fk_sizes_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_sizes_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `hichikala`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hichikala`.`prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`prices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `price` INT NOT NULL,
  `discount` INT NOT NULL DEFAULT 0,
  `discountـexpireـtime` DATETIME NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `patterns_id` BIGINT NULL,
  `sizes_id` BIGINT NULL,
  `products_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `products_id`),
  INDEX `fk_prices_patterns1_idx` (`patterns_id` ASC) VISIBLE,
  INDEX `fk_prices_sizes1_idx` (`sizes_id` ASC) VISIBLE,
  INDEX `fk_prices_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_prices_patterns1`
    FOREIGN KEY (`patterns_id`)
    REFERENCES `hichikala`.`patterns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prices_sizes1`
    FOREIGN KEY (`sizes_id`)
    REFERENCES `hichikala`.`sizes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prices_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `hichikala`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`transactions_has_prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`transactions_has_prices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `count` TINYINT NULL,
  `price` VARCHAR(60) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `transactions_id` BIGINT NOT NULL,
  `prices_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `transactions_id`, `prices_id`),
  INDEX `fk_products_has_transactions_transactions1_idx` (`transactions_id` ASC) VISIBLE,
  INDEX `fk_products_has_transactions_prices1_idx` (`prices_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_transactions_transactions1`
    FOREIGN KEY (`transactions_id`)
    REFERENCES `hichikala`.`transactions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_transactions_prices1`
    FOREIGN KEY (`prices_id`)
    REFERENCES `hichikala`.`prices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`posts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `status` TINYINT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `transactions_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `transactions_id`),
  INDEX `fk_posts_transactions1_idx` (`transactions_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_transactions1`
    FOREIGN KEY (`transactions_id`)
    REFERENCES `hichikala`.`transactions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`colors` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `color_name` VARCHAR(100) NOT NULL,
  `color_code` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hichikala`.`colors_has_patterns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`colors_has_patterns` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `colors_id` BIGINT NOT NULL,
  `patterns_id` BIGINT NOT NULL,
  INDEX `fk_colors_has_patterns_patterns1_idx` (`patterns_id` ASC) VISIBLE,
  INDEX `fk_colors_has_patterns_colors1_idx` (`colors_id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `colors_id`, `patterns_id`),
  CONSTRAINT `fk_colors_has_patterns_colors1`
    FOREIGN KEY (`colors_id`)
    REFERENCES `hichikala`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colors_has_patterns_patterns1`
    FOREIGN KEY (`patterns_id`)
    REFERENCES `hichikala`.`patterns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hichikala`.`blogs_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`blogs_contents` (
  `id` BIGINT NOT NULL,
  `alt` VARCHAR(100) NULL,
  `content` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `blogs_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `blogs_id`),
  INDEX `fk_blogs_images_blogs1_idx` (`blogs_id` ASC) VISIBLE,
  CONSTRAINT `fk_blogs_images_blogs1`
    FOREIGN KEY (`blogs_id`)
    REFERENCES `hichikala`.`blogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hichikala`.`products_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`products_has_categories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `products_id` BIGINT NOT NULL,
  `categories_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `products_id`, `categories_id`),
  INDEX `fk_products_has_category_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_products_has_category_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_category_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `hichikala`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_category_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `hichikala`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`insurances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`insurances` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `expire_time` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `patterns_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `patterns_id`),
  INDEX `fk_insurances_patterns1_idx` (`patterns_id` ASC) VISIBLE,
  CONSTRAINT `fk_insurances_patterns1`
    FOREIGN KEY (`patterns_id`)
    REFERENCES `hichikala`.`patterns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hichikala`.`guarantees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`guarantees` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `expire_time` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `patterns_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `patterns_id`),
  INDEX `fk_warranties_patterns1_idx` (`patterns_id` ASC) VISIBLE,
  CONSTRAINT `fk_warranties_patterns1`
    FOREIGN KEY (`patterns_id`)
    REFERENCES `hichikala`.`patterns` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hichikala`.`ranks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`ranks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `count` TINYINT NOT NULL,
  `status` TINYINT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `customers_id` BIGINT NOT NULL,
  `products_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `customers_id`, `products_id`),
  INDEX `fk_ranks_customers1_idx` (`customers_id` ASC) VISIBLE,
  INDEX `fk_ranks_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_ranks_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `hichikala`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ranks_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `hichikala`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hichikala`.`attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`attributes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(80) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `products_attributes_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `products_attributes_id`),
  INDEX `fk_attributes_products_attributes1_idx` (`products_attributes_id` ASC) VISIBLE,
  CONSTRAINT `fk_attributes_products_attributes1`
    FOREIGN KEY (`products_attributes_id`)
    REFERENCES `hichikala`.`products_attributes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hichikala`.`products_has_attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`products_has_attributes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `attributes_id` BIGINT NOT NULL,
  `products_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `attributes_id`, `products_id`),
  INDEX `fk_products_has_attributes_attributes1_idx` (`attributes_id` ASC) VISIBLE,
  INDEX `fk_products_has_attributes_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_attributes_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `hichikala`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_attributes_attributes1`
    FOREIGN KEY (`attributes_id`)
    REFERENCES `hichikala`.`attributes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`managers_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`managers_logs` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `loggable_type` VARCHAR(255) NOT NULL,
  `loggable_id` BIGINT NOT NULL,
  `action` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `managers_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `managers_id`),
  INDEX `fk_managers_logs_managers1_idx` (`managers_id` ASC) VISIBLE,
  CONSTRAINT `fk_managers_logs_managers1`
    FOREIGN KEY (`managers_id`)
    REFERENCES `hichikala`.`managers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`folders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`folders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `folders_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_folders_folders1_idx` (`folders_id` ASC) VISIBLE,
  CONSTRAINT `fk_folders_folders1`
    FOREIGN KEY (`folders_id`)
    REFERENCES `hichikala`.`folders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`files` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `alt` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `status` TINYINT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `folders_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `folders_id`),
  INDEX `fk_files_folders1_idx` (`folders_id` ASC) VISIBLE,
  CONSTRAINT `fk_files_folders1`
    FOREIGN KEY (`folders_id`)
    REFERENCES `hichikala`.`folders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


-- -----------------------------------------------------
-- Table `hichikala`.`file_relations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hichikala`.`file_relations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `loggable_type` VARCHAR(255) NOT NULL,
  `loggable_id` BIGINT NOT NULL,
  `action` VARCHAR(255) NOT NULL,
  `field` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `files_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `files_id`),
  INDEX `fk_files_has_table_files1_idx` (`files_id` ASC) VISIBLE,
  CONSTRAINT `fk_files_has_table_files1`
    FOREIGN KEY (`files_id`)
    REFERENCES `hichikala`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_persian_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `hichikala`.`managers`
-- -----------------------------------------------------
START TRANSACTION;
USE `hichikala`;
INSERT INTO `hichikala`.`managers` (`id`, `username`, `password`, `name`, `family`, `rate`, `status`, `avatar`, `created_at`, `updated_at`, `email`) VALUES (1, '09157168320', 'm81dc9bdb52d04dc20036dbd8313ed05565b1ae8e371b343827197ce2d5a5a1292fddfc2f', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

COMMIT;

